spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/myblog
    username: root
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  security:
#    user:
#      name: somen
#      password: bag
#      roles: ADMIN